import type { Listing } from "@/types/listing"

// Mock data for development
export const mockListings: Listing[] = [
  {
    id: 1,
    title: "Cozy Apartment in NYC",
    location: "New York, USA",
    address: "123 Broadway, New York, NY",
    price_per_night: 120,
    currency: "USD",
    total_price: 360,
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    ratings: 4.8,
    description:
      "A beautiful apartment in the heart of New York City. This stylish space features modern amenities, a fully equipped kitchen, and is within walking distance to major attractions, restaurants, and public transportation. Perfect for couples or solo travelers looking to explore the city.",
    reviews: 150,
    amenities: [
      "WiFi",
      "Kitchen",
      "Air Conditioning",
      "Washer",
      "Dryer",
      "TV",
      "Heating",
      "Workspace",
      "Elevator",
      "Hair dryer",
    ],
    host: {
      name: "John Doe",
      image: "/placeholder.svg?height=50&width=50",
      is_superhost: true,
    },
    property_type: "Apartment",
  },
  {
    id: 2,
    title: "Luxury Villa with Pool",
    location: "Miami, USA",
    address: "456 Ocean Drive, Miami, FL",
    price_per_night: 350,
    currency: "USD",
    total_price: 1050,
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    ratings: 4.9,
    description:
      "Stunning villa with private pool and ocean views. This luxurious property offers spacious living areas, high-end furnishings, and a gourmet kitchen. Enjoy the outdoor entertainment area with BBQ, lounge by the pool, or take a short walk to the beach. Perfect for families or groups looking for a premium vacation experience.",
    reviews: 87,
    amenities: [
      "Pool",
      "WiFi",
      "Kitchen",
      "Air Conditioning",
      "Parking",
      "TV",
      "Washer",
      "Dryer",
      "Beachfront",
      "BBQ Grill",
    ],
    host: {
      name: "Jane Smith",
      image: "/placeholder.svg?height=50&width=50",
      is_superhost: true,
    },
    property_type: "Villa",
  },
  {
    id: 3,
    title: "Modern Downtown Loft",
    location: "Chicago, USA",
    address: "789 Michigan Ave, Chicago, IL",
    price_per_night: 180,
    currency: "USD",
    total_price: 540,
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    ratings: 4.7,
    description:
      "Stylish loft in downtown Chicago with city views. This contemporary space features high ceilings, large windows, and an open floor plan. The fully equipped kitchen, comfortable sleeping area, and modern bathroom make this the perfect urban retreat. Located in the heart of the city with easy access to restaurants, shopping, and attractions.",
    reviews: 65,
    amenities: [
      "WiFi",
      "Kitchen",
      "Air Conditioning",
      "Gym",
      "Elevator",
      "TV",
      "Washer",
      "Dryer",
      "Doorman",
      "Coffee maker",
    ],
    host: {
      name: "Mike Johnson",
      image: "/placeholder.svg?height=50&width=50",
      is_superhost: false,
    },
    property_type: "Loft",
  },
  {
    id: 4,
    title: "Beachfront Cottage",
    location: "Malibu, USA",
    address: "101 Pacific Coast Hwy, Malibu, CA",
    price_per_night: 275,
    currency: "USD",
    total_price: 825,
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    ratings: 4.9,
    description:
      "Charming cottage with direct beach access. Wake up to the sound of waves in this beautifully renovated beachfront property. The cottage features a cozy living area, well-equipped kitchen, and a spacious deck perfect for watching sunsets. Step right onto the sand from your private patio and enjoy the best of California coastal living.",
    reviews: 112,
    amenities: [
      "WiFi",
      "Kitchen",
      "Beachfront",
      "Patio",
      "BBQ Grill",
      "TV",
      "Parking",
      "Air Conditioning",
      "Heating",
      "Beach essentials",
    ],
    host: {
      name: "Sarah Williams",
      image: "/placeholder.svg?height=50&width=50",
      is_superhost: true,
    },
    property_type: "Cottage",
  },
  {
    id: 5,
    title: "Mountain Cabin Retreat",
    location: "Aspen, USA",
    address: "222 Mountain Road, Aspen, CO",
    price_per_night: 195,
    currency: "USD",
    total_price: 585,
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    ratings: 4.8,
    description:
      "Cozy cabin surrounded by nature with mountain views. This authentic log cabin offers a rustic yet comfortable experience with modern amenities. Enjoy the wood-burning fireplace, fully equipped kitchen, and outdoor hot tub. Located near hiking trails and ski slopes, it's perfect for outdoor enthusiasts in any season.",
    reviews: 78,
    amenities: [
      "WiFi",
      "Fireplace",
      "Kitchen",
      "Hiking Trails",
      "Hot Tub",
      "TV",
      "Parking",
      "Heating",
      "Ski-in/Ski-out",
      "Mountain view",
    ],
    host: {
      name: "Robert Brown",
      image: "/placeholder.svg?height=50&width=50",
      is_superhost: false,
    },
    property_type: "Cabin",
  },
  {
    id: 6,
    title: "Historic Brownstone",
    location: "Boston, USA",
    address: "333 Beacon St, Boston, MA",
    price_per_night: 210,
    currency: "USD",
    total_price: 630,
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    ratings: 4.7,
    description:
      "Elegant brownstone in historic Boston neighborhood. This charming property combines historic architecture with modern comforts. The thoughtfully decorated interior features high ceilings, hardwood floors, and period details. Located in a quiet, tree-lined street within walking distance to parks, restaurants, and cultural attractions.",
    reviews: 92,
    amenities: [
      "WiFi",
      "Kitchen",
      "Washer",
      "Dryer",
      "Garden",
      "TV",
      "Heating",
      "Air Conditioning",
      "Fireplace",
      "Books and reading material",
    ],
    host: {
      name: "Emily Davis",
      image: "/placeholder.svg?height=50&width=50",
      is_superhost: true,
    },
    property_type: "Townhouse",
  },
  {
    id: 7,
    title: "Desert Oasis with Hot Tub",
    location: "Scottsdale, USA",
    address: "444 Cactus Rd, Scottsdale, AZ",
    price_per_night: 165,
    currency: "USD",
    total_price: 495,
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    ratings: 4.6,
    description:
      "Modern home with private hot tub and desert views. This contemporary desert retreat offers a peaceful setting with stunning landscape views. The property features an open concept living area, fully equipped kitchen, and a private patio with hot tub. Perfect for those looking to relax and enjoy the beautiful Arizona scenery.",
    reviews: 54,
    amenities: [
      "WiFi",
      "Hot Tub",
      "Pool",
      "Kitchen",
      "Air Conditioning",
      "TV",
      "Parking",
      "Washer",
      "Dryer",
      "Outdoor shower",
    ],
    host: {
      name: "David Wilson",
      image: "/placeholder.svg?height=50&width=50",
      is_superhost: false,
    },
    property_type: "House",
  },
  {
    id: 8,
    title: "Lakefront Cabin",
    location: "Lake Tahoe, USA",
    address: "555 Lakeshore Dr, Lake Tahoe, CA",
    price_per_night: 230,
    currency: "USD",
    total_price: 690,
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    ratings: 4.9,
    description:
      "Rustic cabin with stunning lake views and private dock. This traditional lake cabin offers a quintessential waterfront experience with modern comforts. Enjoy the cozy interior with wood-burning fireplace, fully equipped kitchen, and panoramic lake views. The private dock provides easy access for swimming and water activities. Perfect for a relaxing getaway in nature.",
    reviews: 103,
    amenities: [
      "WiFi",
      "Fireplace",
      "Kitchen",
      "Dock",
      "Kayaks",
      "TV",
      "Parking",
      "Heating",
      "Waterfront",
      "Outdoor furniture",
    ],
    host: {
      name: "Lisa Thompson",
      image: "/placeholder.svg?height=50&width=50",
      is_superhost: true,
    },
    property_type: "Cabin",
  },
]

